### ISSUE TITLE
Añadir un arbol binario al proyecto

### ISSUE THREAD

**Issue by CarlosIzarra09** [AnguloVallleWilliam/FileExplorer#1]
Añadir una clase Arbol Binario (Arbol.hpp) al proyecto para trabajar con el.

**Comment by CarlosIzarra09** [comment]
Verifico que añadiste el arbol binario. Doy este issue por finalizado

**Comment by AnguloDev10** [comment]
Este arbol ya fue cambiado a AVL

**Comment by CarlosIzarra09** [comment]
Por mi.
