### ISSUE TITLE
Implementar metodo que reinicie al arbol binario con sus valores por defecto.

### ISSUE THREAD

**Issue by CarlosIzarra09** [AnguloVallleWilliam/FileExplorer#11]
Implementar un metodo que elimine todos los nodos del arbol binario utilizado y que además valide que este arbol pueda ser utilizado para una nueva insercion de elementos en el.

**Comment by CarlosIzarra09** [comment]
Realizado correctamente.

**Comment by AnguloDev10** [comment]
Revisado en su totalidad
