### ISSUE TITLE
Implementar boton actualizar en el formulario.

### ISSUE THREAD

**Issue by CarlosIzarra09** [AnguloVallleWilliam/FileExplorer#13]
Intentar implementar botón que al presionarlo valide la dirección de una carpeta ingresado en el , otorgue el texto ingresado en el txtbox al programa para que genere los objetos archivos con sus respectivos atributos y de ello añada esos elementos al arbol binario.

**Comment by CarlosIzarra09** [comment]
Realizado.

**Comment by AnguloDev10** [comment]
Implementado el formulario, validaciones revisadas por el grupo
