### ISSUE TITLE
Filtrado de datos por columnas.

### ISSUE THREAD

**Issue by CarlosIzarra09** [AnguloVallleWilliam/FileExplorer#16]
Esta tarea consiste en realizar una consulta filtrando por:
1.- Nombres considerando los criterios de:
a. Empieza con
b. Finaliza con
c. Contiene
2.- Tamaño de archivo considerando los criterios de:
a. Mayor.
b. Menor.
c. Igual a.

**Comment by CarlosIzarra09** [comment]
@oscardas se encargará de
1.- Nombres considerando los criterios de:
a. Empieza con
b. Finaliza con
c. Contiene
2.- Tamaño de archivo considerando los criterios de:
a. Mayor a ......

**Comment by CarlosIzarra09** [comment]
yo me encargaré de 
2.- Tamaño de archivo considerando los criterios de:
b. Menor a .......

y @AnguloVallleWilliam 
c. Igual a.

**Comment by CarlosIzarra09** [comment]
Implementé el fitrado de nombres por empieza en "",
les dejé la base para que se guien
oscar cambiaras conmigo por el
2.- Tamaño de archivo considerando los criterios de:
b. Menor a .......

**Comment by OscarFloresP** [comment]
Filtros restantes finalizados.
