### ISSUE TITLE
Mejorar el aspecto visual del programa segun nuestro objetivo planteado.

### ISSUE THREAD

**Issue by CarlosIzarra09** [AnguloVallleWilliam/FileExplorer#21]
Aplicar el diseño de ingeniería para producir soluciones que satisfagan necesidades específicas con consideración de salud pública, seguridad y bienestar, así como factores globales, culturales, sociales,
ambientales y económicos.

**Comment by AnguloDev10** [comment]
El aspecto visual esta correcto hasta este momento.Listo

**Comment by CarlosIzarra09** [comment]
jajaja q gracioso, ya enserio
