### ISSUE TITLE
Implementar metodo de retorno de datos del nodo de una arbol.

### ISSUE THREAD

**Issue by CarlosIzarra09** [AnguloVallleWilliam/FileExplorer#7]
Sera necesario crear un metodo que nos retorne los datos de un nodo del arbo, como nombre de archivo, tamaño, fecha, extension.

**Comment by CarlosIzarra09** [comment]
Cumplido parcialmente, falta implementar el lambda para retorno de la fecha de creacion del archivo

**Comment by CarlosIzarra09** [comment]
Lambda por fecha cumplido por Angulo.

**Comment by AnguloDev10** [comment]
El criterio de indexado ha sido mejorado en su totalidad
