### ISSUE TITLE
Implementar los elementos del formulario que usaremos en el.

### ISSUE THREAD

**Issue by CarlosIzarra09** [AnguloVallleWilliam/FileExplorer#8]
Esto incluye un ListView, Buttons, labels , textbox , etc

**Comment by CarlosIzarra09** [comment]
Realizado para lo que se preveía del prototipo.

**Comment by AnguloDev10** [comment]
Renderizado,corrigiendo cierots errores

**Comment by AnguloDev10** [comment]
Corregido, antes del hito 2
